Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -1,101 +1,90 @@
-name: Build, Deploy, and Manage PR Previews
+# Sample workflow for building and deploying a Next.js site to GitHub Pages
+#
+# To get started with Next.js see: https://nextjs.org/docs/getting-started
+#
+name: Deploy Next.js site to Pages
 
 on:
+  # Runs on pushes targeting the default branch
   push:
-    branches:
-      - master
-  pull_request:
-    branches: 
-      - master
-  pull_request_target:
-    types: [closed]
+    branches: ["main"]
 
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
 permissions:
-  contents: write
+  contents: read
   pages: write
   id-token: write
-  issues: write
-  pull-requests: write
+
+# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
+# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
+concurrency:
+  group: "pages"
+  cancel-in-progress: false
 
 jobs:
-  build-and-deploy:
-    runs-on: ubuntu-latest
+  # Build job
+  build:
+    runs-on: [self-hosted, solinas-ubuntu_20_04]
     steps:
-    - uses: actions/checkout@v2
-
-    - name: Setup Node.js
-      uses: actions/setup-node@v2
-      with:
-        node-version: '18' 
-
-    - name: Install Dependencies
-      run: npm install
-
-    - name: Build and Export (Static Site)
-      run: npm run build
-      env:
-        # Use environment variables as needed for your build process
-        NEXT_PUBLIC_PR_NUMBER: ${{ github.event.pull_request.number }}
-
-    - name: Deploy to GitHub Pages (Production)
-      if: github.event_name == 'push'
-      uses: JamesIves/github-pages-deploy-action@4.1.4
-      with:
-        branch: gh-pages
-        folder: out
-        token: ${{ secrets.GITHUB_TOKEN }}
-        # No target-folder for production deployment
-
-    - name: Deploy PR Preview to GitHub Pages
-      if: github.event_name == 'pull_request'
-      uses: JamesIves/github-pages-deploy-action@4.1.4
-      with:
-        branch: gh-pages
-        folder: out
-        token: ${{ secrets.GITHUB_TOKEN }}
-        target-folder: pr-${{ github.event.pull_request.number }}
-
-    - name: Comment PR Preview URL
-      if: github.event_name == 'pull_request'
-      uses: actions/github-script@v5
-      with:
-        script: |
-          const issueNumber = context.issue.number;
-          const prPreviewUrl = `https://omptech.github.io/nextra-demo/pr-${issueNumber}`;
-          const message = `🚀 PR preview is available at ${prPreviewUrl}`;
-          github.rest.issues.createComment({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            issue_number: issueNumber,
-            body: message
-          });
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-
-  cleanup-preview:
-    if: github.event_name == 'pull_request_target' && github.event.action == 'closed'
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          ref: 'gh-pages'
-
-      - name: Configure Git
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Detect package manager
+        id: detect-package-manager
         run: |
-          git config user.name "omptech"
-          git config user.email "omprakashlodhi38@gmail.com"
-
-      - name: Cleanup PR Preview
-        run: |
-          PR_NUMBER=${{ github.event.pull_request.number }}
-          DIRECTORY="pr-$PR_NUMBER"
-          # Find the directory in the gh-pages branch and delete it if found
-          git fetch origin gh-pages
-          git checkout gh-pages
-          if [ -d "$DIRECTORY" ]; then
-          echo "Directory $DIRECTORY found, deleting..."
-          git rm -rf "$DIRECTORY"
-          git commit -m "Remove preview for PR #$PR_NUMBER"
-          git push origin gh-pages
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
           else
-          echo "Directory $DIRECTORY not found, skipping deletion."
+            echo "Unable to determine package manager"
+            exit 1
           fi
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "18"
+      - name: Setup Pages
+        uses: actions/configure-pages@v4
+        with:
+          static_site_generator: next
+      - name: Restore cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+      - name: Install yarn
+        run: npm install -g yarn
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Static HTML export with Next.js
+        run: ${{ steps.detect-package-manager.outputs.runner }} export
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v2
+        with:
+          path: ./out
+
+  # Deployment job
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: [self-hosted, solinas-ubuntu_20_04]
+    needs: build
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v2
